services:
  database:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-db

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  # app:
  #   build: .
  #   container_name: api
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     - database
