services:
  database:
    image: bitnami/postgresql
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - 5432:5432

  app:
    build: .
    container_name: api
    ports:
      - 3333:3333
    depends_on:
      - database
